### ISSUE TITLE
rules items could look more like buttons

### ISSUE THREAD

**Issue by stephanlindauer** [headione/criticalmaps-ios#4]
![image](https://cloud.githubusercontent.com/assets/1323145/9295007/3b6b72d4-445f-11e5-951a-57236fa37f41.png)

maybe it would make it more obviuos that its clickable if there would be a border or background color.

**Comment by stephanlindauer** [comment]
or maybe just a suffix like ">>"

**Comment by headione** [comment]
that's true, i inserted a single ">" for now
